name: 'sound-ci-helper'
description: 'Setup sound on CIs'
author: Eric Larson
branding:
  icon: 'speaker'
  color: 'blue'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/auto.sh
      shell: bash
