name: 'Test'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  job:
    name: ${{ matrix.os }} ${{ matrix.python}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, windows-2022, windows-2019, macos-14, macos-13, macos-12]
        python: ['3.12', '3.8']
    defaults:
      run:
        shell: bash -e {0}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - run: pip install sounddevice
      - run: python -m sounddevice
      - run: |
          set -xeo pipefail
          python -m sounddevice | grep "[82] out"
        name: Check that there is some output device
      - run: sleep 10
      - run: |
          set -xeo pipefail
          python -m sounddevice | grep "[82] out"
        name: Check that there is some output device after sleep
