name: 'Test'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  job:
    name: ${{ matrix.os }} ${{ matrix.python}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04-arm, ubuntu-24.04, ubuntu-22.04, windows-2025, windows-2022, macos-15, macos-14, macos-13]
        python: ['3.13', '3.10']
    defaults:
      run:
        shell: bash -e {0}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - run: pip install sounddevice
      - run: python -m sounddevice
      - run: |
          output=$(python -m sounddevice --list-devices)
          if [ -z "$output" ]; then
            echo "Error: sounddevice --list-devices returned no output"
            exit 1
          fi
          echo "$output"
